-- Historical compatibility marker.
--
-- The original file was an explicitly labelled draft that attempted to add
-- uuid user_id columns. The active schema already used non-null text user_id
-- columns, so `add column if not exists` did not change their type and the
-- subsequent uuid-to-text policies could not compile.
--
-- Production Auth/RLS activation is implemented by:
--   20260724121000_enable_authenticated_rls.sql
--
-- That migration preserves the text storage contract, compares
-- auth.uid()::text, covers detailed workout tables, rejects unmapped legacy
-- owners, revokes anon table access, and creates complete CRUD policies.
select 1;
